disable compression by default
idlab-discover/easy-openvpn-server pull request #24
Opened 2023-04-13 06:18 UTC by lyoneel

Disable by default to avoid Compression oracle attacks,
see: https://superuser.com/questions/1686651/why-is-compression-not-recommended-in-openvpn

2023-04-17 14:54 UTC, merlijn-sebrechts requested changes
Thanks for this PR, good work!

I can't accept it in this state because we need a way to support existing installs with existing client configs. We can't just turn off compression for existing installs during an update since that will break all clients. I propose the following:

* On new installs, compression is off by default.
* On existing upgrades, compression is on by default.
* We give the users of existing installs a way to turn off compression

A second issue is that I don't want to give new users a config option to turn on compression. This is an opinionated OpenVPN server and insecure config should simply not be supported.

So I propose something like this:

* Remove the setting
* In `get_compress()`, check if a server config file already exists and whether it has compression. If it does, then return that compression, otherwise return `no`.

What do you think of this?

2023-04-17 15:13 UTC, merlijn-sebrechts commented
Actually, it seems like [`allow-compression asym` and `compress no`](https://community.openvpn.net/openvpn/wiki/Compression) is what we want for server configs, and compression turned off for new client configs. That way, we can support existing clients and new clients.

So then my requested changes are to switch to `compress asym` server-side, no compression client-side, and remove the option to change compression.

2023-04-17 15:16 UTC, merlijn-sebrechts commented
We might need to upgrade to core22 for this to work.

2023-04-18 12:17 UTC, lyoneel commented
I'm having a lot of trouble trying to test changes, at the moment Im editing manually config files, because snapcraft is not working for me, cant build the snap. 

I got additional changes that are not tested yet, Ill take a look you suggestions whenever have a little time.

Sorry for the delays

2023-04-18 23:27 UTC, lyoneel commented
> Actually, it seems like [`allow-compression asym` and `compress no`](https://community.openvpn.net/openvpn/wiki/Compression) is what we want for server configs, and compression turned off for new client configs. That way, we can support existing clients and new clients.
> 
> So then my requested changes are to switch to `compress asym` server-side, no compression client-side, and remove the option to change compression.

Let me know If I misunderstood something.

1-. set on server template allow-compress asym
2-. set on client template compress no
3-. remove get_compress function
4-. upgrade to core22

Regarding point 3, my ovpn client complains when compress is set to "no", Ill remove the line instead.

2025-01-09 16:15 UTC, ghost commented
> > Actually, it seems like [`allow-compression asym` and `compress no`](https://community.openvpn.net/openvpn/wiki/Compression) is what we want for server configs, and compression turned off for new client configs. That way, we can support existing clients and new clients.
> > So then my requested changes are to switch to `compress asym` server-side, no compression client-side, and remove the option to change compression.
> 
> Let me know If I misunderstood something.
> 
> 1-. set on server template allow-compress asym 2-. set on client template compress no 3-. remove get_compress function 4-. upgrade to core22
> 
> Regarding point 3, my ovpn client complains when compress is set to "no", Ill remove the line instead.
> 
> When this PR is done, I would like to you or someone try this snap from the snap, because I cannot build in my pc right now, snapcraft command refuses to work.

Is this in a state that is ready to be tested?

2025-02-10 13:34 UTC, closed without merging